### ISSUE TITLE
disable_read argument does not work with vault_kv_secret_v2

### ISSUE THREAD

**Issue by reganmcdonaldpri** [hashicorp/terraform-provider-vault#1668]
### Terraform Version
v1.3.3

### Affected Resource(s)
vault_kv_secret_v2

### Terraform Configuration Files
```hcl
resource "vault_kv_secret_v2" "this" {
  mount        = "secret"
  name         = var.path
  disable_read = true
  data_json    = jsonencode({})
}
```

### Expected Behavior
With disable_read set to true, Terraform should not read an existing secret or detect drift such as modified data or added keys.

### Actual Behavior
After new data is added to the secret, Terraform detects drift and removes new keys/data.

Terraform will perform the following actions:
```hcl
  # module.test_secret.vault_kv_secret_v2.this will be updated in-place
  ~ resource "vault_kv_secret_v2" "this" {
      + data                = (sensitive value)
        id                     = "secret/data/project1/sandbox/new_test_secret"
      + metadata        = (known after apply)
        name                = "project1/sandbox/new_test_secret"
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
1. Create vault_kv_secret_v2 with empty json_data
2. Add data to secret
3. Rerun Terraform

**Comment by vinay-gopalan** [comment]
Hi @reganmcdonaldpri, thanks for opening this issue. This drift detection is expected, since it comes from the diff between what you have in your config and what you have in your TF state, and is in-built into the TF SDK. It is unrelated to the `disable_read` parameter in this case, since the purpose of that field is to avoid reading the secret from Vault and avoid setting the computed `data` and `metadata` attributes to prevent drifts. If you take a look at your `terraform.tfstate` file, you should see the `disable_read` field working, since the computed attributes of `data` and `metadata` would both be unchanged (`null` if `disable_read` was always true). 

The drift you see above is coming from the TF SDK, and always takes place when there is a change detected between your TF config file and your TF state. The secret is not being read from Vault in that case. Going to close this issue, but please feel free to open another issue if you face any other problems. Thanks!

**Comment by wolfmd** [comment]
Hello! Apologies for poking on a closed issue, but I've run into a similar predicament when referencing the output of another terraform resource in the `data_json`. Once the first apply is run, the secret appears in vault as expected. However, once another plan is run, a diff is detected. If applied, the same secret is pushed to the kv. This feels similar to https://github.com/hashicorp/terraform-provider-vault/issues/842 but I'm finding it difficult to locate any diff that could be picked up. Using the ignore_changes, even on the data_json itself doesn't seem to help

```
provider "vault" {
  address      = "https://vault.mydomain.com:8200"
  ca_cert_file = "/etc/certs/mycert.crt"

  auth_login {
    path = "auth/login"

    parameters = {
      role = "service"
      jwt  = file("/var/run/token")
    }
  }
}

resource "some_resource" "my_cool_resource" {
...
}

resource "vault_kv_secret_v2" "my_cool_resource_secret" {
  mount        = "kvv2"
  name         = "my/super/cool/secret"
  disable_read = true
  data_json = jsonencode({
    data = "${some_resource.my_cool_resource.secret}"
  })
  lifecycle {
    ignore_changes = [custom_metadata, options, data_json]
  }
}

```
which returns 
```
  ~ resource "vault_kv_secret_v2" "my_cool_resource_secret" {
      + data                = (sensitive value)
        id                     = "kvv/data/my/super/cool/secret"
      + metadata       = (known after apply)
        name               = "my/super/cool/secret"
        # (5 unchanged attributes hidden)
    }
```
on each plan

Perhaps there a way to tell Terraform that nothing has changed with the upstream secret and that the secret is fine as it is.
