### ISSUE TITLE
Cert Auth / PKI: Missing some options

### ISSUE THREAD

**Issue by tmanninger** [hashicorp/terraform-provider-vault#1696]
I missing some options:

Endpoint: /auth/cert/config
Parameter: enable_identity_alias_metadata (bool: false)
Dokumention: https://developer.hashicorp.com/vault/api-docs/auth/cert

Terraform modul: vault_pki_secret_backend_crl_config
Parameters: 
- ocsp_disable (bool: false)
- ocsp_expiry (string: "12h")
- auto_rebuild (bool: false)
- auto_rebuild_grace_period (string: "12h")
- enable_delta (bool: false)
- delta_rebuild_interval (string: "15m")

Terraform module: vault_cert_auth_backend_role
Parameters:
- allowed_metadata_extensions (array:[])

**Comment by redat00** [comment]
Hi ! 

I think this issue was wrongly closed @benashz. Only 1 of the 4 mentionned PR has been merged. Leaving the two that are still open dangling all by themselves without any related issues. I can assure you the lack of ability to configure a cert backend through Terraform is still well present unfortunately...

Would love to see this work finally being merged or at least reviewed in a first time. 

Thanks in advance !
