### ISSUE TITLE
auth_login_aws should always try to assume role if aws_role_arn  value is provided

### ISSUE THREAD

**Issue by modesvops** [hashicorp/terraform-provider-vault#1808]
### Terraform Version
Terraform version: 1.4.2

### Affected Resource(s)
- provider

### Terraform Configuration Files
```hcl
provider "vault" {
  address = "https://vault.company.com/"
  auth_login_aws {
    role         = "admin"
    aws_region   = "eu-central-1"
    aws_role_arn = "arn:aws:iam::44455xxxx552:role/my-role"
  }
}
```

### Debug Output
After some debugging I find out that go-secure-stdlib is used to create aws session. This lib only support assuming role if web identity token is provided 
![image](https://user-images.githubusercontent.com/87967053/228588225-ad57fa82-52ab-4d41-86c1-662607e2fda4.png)
I think vault provider should not ignore aws_role_arn if web identity token is not provider and should try to assume role with aws_access_key keys or profile.

### Panic Output
n/a

### Expected Behavior
Vault provider should assume aws role before trying to connect to vault.

### Actual Behavior
Role is ignored and default profile credentials used.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
n/a

### References
n/a

**Comment by davesade** [comment]
We are also getting burned by this. The code in question is 2 years old, I find it hard to believe no one ever tried to login to the Vault with assumed IAM role. Would be awesome to have this fixed.

**Comment by tyhunt99** [comment]
The newer versions of `go-secure-stdlib` appear to handle this better now. Could be as simple as updating the version the provider is using.

**Comment by elcomtik** [comment]
@fairclothjm Did you tested that updated go-secure-stdlib works? I'm unable to verify fix.

**Comment by martinlindner** [comment]
@fairclothjm @elcomtik This is apparently still broken for me too. In a scenario where we're setting `aws_profile` and `aws_role_arn`, the provider still seems to authenticate with the profile's original role instead of assuming the specified one.

I wonder if updating `go-secure-stdlib/awsutil` yet again, to the `v2.0.0` version that [was just released](https://github.com/hashicorp/go-secure-stdlib/releases/tag/awsutil%2Fv2.0.0), might have a positive impact here.
