### ISSUE TITLE
resource_ssh_secret_backend_role not mentioned in CHANGELOG for 1.6.0

### ISSUE THREAD

**Issue by jeffb4** [hashicorp/terraform-provider-vault#297]
### Terraform Version
HEAD

### Affected Resource(s)
resource_ssh_secret_backend_role

### Expected Behavior
Documented in CHANGELOG

### Actual Behavior
Not mentioned in CHANGELOG

**Comment by benashz** [comment]
`resource_ssh_secret_backend_role` is fully documented. We don't tend to retroactively update the changelog this far back in time.

**Comment by jeffb4** [comment]
Understandable, Ben. Maybe doc issues could get triaged in fewer than 3 years, though, going forward.

**Comment by hsimon-hashicorp** [comment]
> Understandable, Ben. Maybe doc issues could get triaged in fewer than 3 years, though, going forward.

We hear you - and that's why I'm here! I started in May of last year, and my job is to help triage and assist the engineering team in handling issues in a more timely manner. HashiCorp is continuing to work to improve in this sort of scenario, and we appreciate the fact that our community cares enough to interact with us here. :)
