### ISSUE TITLE
vault_auth_backend should not add final / to path

### ISSUE THREAD

**Issue by rberlind** [hashicorp/terraform-provider-vault#46]
### Terraform Version
v0.11.0

### Affected Resource(s)
- vault_auth_backend

### Terraform Configuration Files
```hcl
resource "vault_auth_backend" "k8s" {
  type = "kubernetes"
  path = "acs-dev"
}

output "vault-k8s-auth-backend" {
  value = "${vault_auth_backend.k8s.path}"
}
```

### Expected Behavior
The Vault provider should set the path exactly to what I specified without adding final "/".

### Actual Behavior
The Vault provider added final "/" to the path, giving "acs-dev/".  I don't want "/" in the path. If path were a computed attribute, I would not necessarily object.  But since path is something I am setting, I feel that the Vault Provider should not change what I set.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @rberlind! Thanks for pointing this out.

As far as I can tell, this slash is actually being added by the Vault server itself rather than by the provider. I agree though that it's strange for the value of a configuration-provided attribute to be changed. There is [some code in place to prevent this change causing a permanent diff](https://github.com/terraform-providers/terraform-provider-vault/blob/9077e4488809ccfea8373c2dd270b9783ddb39c1/vault/resource_auth_backend.go#L46-L48), which is how this provider is getting away with altering a user-provided value in this way.

We can hopefully introduce some logic into the `Read` function for this resource so that it can recognize whether the user-provided value has a slash and then trim it off the API response if not. While such behavior would normally create risk of confusing behavior when changes are made outside of Terraform, that's not an issue in this case because an auth backend's path cannot be changed without unmounting and remounting it.

**Comment by rberlind** [comment]
Thanks.  If we do change the way it works, let's be sure to document in change notes.  I would have to change a demo I have that uses it since I currently don't add a slash but would then have to if the slash were no longer added by Terraform.

**Comment by benashz** [comment]
The provider no longer includes the `/` trailing slash in the `path` attribute. Closing this issue out.
