### ISSUE TITLE
vault_generic_secret type=kv-v2 first write fails status 400 Upgrading from non-versioned to versioned data. "This backend will be unavailable for a brief period and will resume service shortly."

### ISSUE THREAD

**Issue by smurfralf** [hashicorp/terraform-provider-vault#677]
# Terraform Version
v0.12.20
### Affected Resource(s)
- vault_generic_secret

### Terraform Configuration Files
```hcl
variable "users" {
  description = "list of users to set up"
  type        = map(string)
  default = {
    "user"  = "vault-user"
    "admin" = "vault-admin"
  }
}

resource "vault_mount" "secret" {
  path        = "mysecrets"
  type        = "kv-v2"
  description = "store key/value secret data"
}

resource "random_password" "user_pwd" {
  for_each    = var.users
  length      = 16
  special     = false
  min_upper   = 1
  min_lower   = 1
  min_numeric = 1
}

resource "vault_generic_secret" "logins" {
  for_each   = var.users
  path       = "mysecrets/realm/users/${each.key}"
  data_json  = <<-EOT
    {
	"username":   "${each.key}",
	"initialpwd": "random_password.user_pwd[each.key].result",
	"memberof":   "${each.value}"
    }
    EOT
  depends_on = [vault_mount.secret]
}
```

### Debug Output
```
  vault_generic_secret.logins["vault-user"]: Creating...
  vault_generic_secret.logins["vault-admin"]: Creating...
  vault_generic_secret.logins["vault-admin"]: Creation complete after 1s [id=mysecrets/realm/users/vault-admin]

 Error: error writing to Vault: Error making API request.
 URL: PUT https://vault.gitlab-ci.mydomain.net:8200/v1/mysecrets/data/realm/users/vault-user
 Code: 400. Errors:
 * Upgrading from non-versioned to versioned data. This backend will be unavailable for a brief period and will resume service shortly.
   on vault_config/terraform/users.tf line 53, in resource "vault_generic_secret" "logins":
   53: resource "vault_generic_secret" "logins" {
```

### Expected Behavior
First insert to kv-v2 should have succeeded along with the following ones.

### Actual Behavior
First insert failed with status 400, second insert succeeded. This does not occur on every run. I'd speculate it depends on the speed at which the vault server is running.

### Steps to Reproduce
1. create spec files that enable a new kv-v2 endpoint then insert  secrets into it.
2. `terraform apply`

### Discussion
Its not clear why vault engages in a "upgrade from non-versioned to versioned data" when the endpoint has just been enabled with type=kv-v2. You'd think it would be set up as a versioned data endpoint from the get-go. Given that it does engage in this behavior, terraform-provider-vault should internally retry the secret write when this error is returned from vault.

**Comment by johnnybubonic** [comment]
i'd have to have someone from HashiCorp confirm as i don't know Go, but this seems to me that how KV2 mounts are enabled is that they're first created as KV1 and then versioning is added.

I was getting this same behaviour (I primarily use python's hvac library with Vault), also with some inconsistent results. It would occur on my desktop (a beast of a machine), but not my laptop (a less beastly machine).

I found that simply adding a `time.sleep(2)` (2 second sleep) after the mount creation before trying to write a secret to it has reduced my reproducibility to 0%. YMMV, obviously, but this seems to be a timing conflict for sure - at least in my case.

The obvious fix for root cause here would be to have a secrets engine be created as version 2 initially rather than as a procedure.

**Comment by queglay** [comment]
I see this same error each time I enable a kv secrets engine (initialise it) through the web UI too. This is using Vault 1.5.5

**Comment by disser4** [comment]
I got the same error and reran without an issue. It looks like you can't add a secret to the mount while it's being created.
