### ISSUE TITLE
data.vault_generic_secret requires new plan and apply on every run

### ISSUE THREAD

**Issue by jravetch** [hashicorp/terraform-provider-vault#873]
### Terraform Version
0.13.3

### Affected Resource(s)
Please list the resources as a list, for example:
-  data.vault_generic_secret

### Terraform Configuration Files
```hcl

data "vault_generic_secret" "gcp_oauth_token" {
  path = "gcp/token/${local.token_name}"
}

provider "google" {
  version      = "~> 3.39.0"
  project      = local.project_id
  access_token = data.vault_generic_secret.gcp_oauth_token.data["token"]
}
```
# Debug Output
```
data.vault_generic_secret.gcp_oauth_token will be read during apply
 (config refers to values not yet known)
 <= data "vault_generic_secret" "gcp_oauth_token"  {
      ~ data             = (sensitive value)
      ~ data_json        = (sensitive value)
        id               = "gcp/token/xxx"
        lease_duration   = 0
        lease_renewable  = false
        lease_start_time = "RFC5559"
        path             = "gcp/token/xxx"
        version          = -1
    }
```
We are on 2.14 with tf 0.13.3 and we are seeing some regression of #849 whereby the `data.vault_generic_secret` is read every plan and requires a new plan/apply. Is it possibly related to #844 ?  Thanks!
```

### Expected Behavior
No new plan

### Actual Behavior
New plan and apply

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by catsby** [comment]
Hello - can you share what `local` represents in this configuration? 

```hcl
data "vault_generic_secret" "gcp_oauth_token" {
  path = "gcp/token/${local.token_name}"
}
```

**Comment by jravetch** [comment]
This is the name of the oauth token used by tfe, which is stored in vault, i.e. `gcp-${local.env}-tfe`.  Each workspace has it's own token.

**Comment by jravetch** [comment]
@catsby Any update?  This issue is really causing us pain.  I noticed the `lease_start_time` keeps changing, since these are oauth tokens.  Could that be what's causing the diff on every plan?

**Comment by catsby** [comment]
Where is the `lease_start_time` changing? I don't see that shown above, are there more details you could share around that? 

Also, does this diff above show if you were to hardcode the token name in the configuration? I'm not suggesting you do long term but just to see if the `${local.token_name}` is playing more of a factor

**Comment by jravetch** [comment]
When running a plan we see this:

```
 <= data "vault_generic_secret" "star_ssl_crt"  {
        data             = (sensitive value)
        data_json        = (sensitive value)
        id               = "secret/star_crt/star.root.com"
        lease_duration   = 72000
        lease_renewable  = false
      ~ lease_start_time = "RFC4449" -> "RFC5559"
        path             = "secret/star_crt/star.root.com"
        version          = -1
    }
```
Using either `${local.token_name}` or the actual token name still causes these diffs.

**Comment by stpierre** [comment]
We're seeing the same thing as @jravetch on Terraform 0.13.4 and Vault provider 2.15. Pinning our Vault provider at 2.14 prevents the issue:

```
terraform {
  required_providers {
    vault = {
      source = "hashicorp/vault"
      version = "~> 2.14, != 2.15"
    }
  }
}
```

**Comment by jravetch** [comment]
We are seeing the problem with 2.14 as well.

**Comment by husunal** [comment]
We have the same issue with Terraform 0.13, Terraform 0.12.29 works as expected.

**Comment by jravetch** [comment]
@catsby Any update on this?

**Comment by stpierre** [comment]
Turns out for us that pinning to Terraform 0.13.4 and Vault provider 2.14 only *usually* avoids the issue; it *mostly* doesn't happen, but still does occasionally. Seeing the same thing with Terraform 0.13.5 as well.

**Comment by jravetch** [comment]
Is there any solution?  I've pinned tf 0.13.3 and vault provider to 2.14 and each run has a new diff.

**Comment by wernerb** [comment]
Still a problem on terraform 0.13.6 and vault 2.18

**Comment by bucklander** [comment]
Same issue surfaced during TF `0.12` to `0.13` migration. Currently on TF `0.13.4` and [latest] Vault provider version `2.18`.

**Comment by rjhornsby** [comment]
Terraform 0.15.1, vault provider 2.19.1, aws provider 3.38.0.

It's taken me a while to figure out, but we're running into the same problem where the `lease_start_time` value keeps changing - ie it wants to switch right now from `RFC1119` to `RFC3339.` Perhaps not coincidentally, 1119 is NTP and 3339 is timestamps. 4449 is something IPv6 and 5559 is something about network congestion so it seems more random than just specifically date/time related RFCs.

I don't think it matters, but for completeness because the OP mentioned GCP, in our case we're using TF and Vault with AWS Secrets Manager.

**Comment by awh** [comment]
@catsby @rjhornsby Whilst #770 undoubtedly fixes _a_ bug, it sadly doesn't fix the problem described in the title of this issue - we are seeing persistent drift on every plan even when there are no other changes:

```
  # data.vault_generic_secret.REDACTED will be read during apply
  # (config refers to values not yet known)
 <= data "vault_generic_secret" "REDACTED"  {
        data             = (sensitive value)
        data_json        = (sensitive value)
        id               = "REDACTED"
        lease_duration   = 0 
        lease_renewable  = false
      ~ lease_start_time = "2022-03-07T10:57:45Z" -> "2022-03-07T10:57:51Z"
        path             = "REDACTED"
        version          = -1
    }  
```

Note how close the timestamps are to each other - in every case, they're both contemporaneous with the run and are only seconds apart.

In our environment we manage many scores of workspaces and frequently commit refactorings to the HCL which should result in no-op plans, but this behaviour means that every time we do it we end up locking them all and they all have to be inspected and discarded by hand. It's also confusing for our product teams when they see unexpected changes in their workspaces.

We tried adding a lifecycle block to ignore the changes to this field, but received this error:

```
Error: Unsupported lifecycle block

  on main.tf line 45, in data "vault_generic_secret" "eks-dockerhub-pull-token":
  45:   lifecycle {

Data resources do not have lifecycle settings, so a lifecycle block is not
allowed.
```

This is a persistent thorn in our side and we would be very grateful for a solution. If no-one has any better ideas, would the maintainers look favourably on a PR that adds a configuration option to the provider that causes this field to be omitted? I suspect it would be less effort for us to implement than a tool which enumerates the TFE REST API and auto-discards empty plans, which is probably what we'll end up creating if this doesn't get addressed at source.

PS the [Vault provider documentation](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/data-sources/generic_secret#lease_start_time) for the `lease_start_time` field says _"Provided only as a convenience"_ which is ironic because for us at least it contains no useful information and is causing a tremendous amount of inconvenience :sweat_smile: Is anyone even using this value?

**Comment by FalconerTC** [comment]
Would love to see a resolution here! Or some way of ignoring it, since lifecycle isn't supported for Data resources

**Comment by vinay-gopalan** [comment]
TFVP v3.5.0 added a new configuration field `with_lease_start_time` to the `vault_generic_secret` data source that allows users to toggle the `lease_start_time` field. If `with_lease_start_time` is set as false, the field `lease_start_time` is not set to the TF state. This should hopefully resolve any constant diffs that arise. Please feel free to reopen another issue if the problem still persists, thanks!

**Comment by imriz** [comment]
@vinay-gopalan I am still seeing it with 3.5.0 and `with_lease_start_time` set to false.
Plan after refresh:
```
 <= data "vault_generic_secret" "passwords"  {
      + data                  = (sensitive value)
      + data_json             = (sensitive value)
      + id                    = (known after apply)
      + lease_duration        = (known after apply)
      + lease_id              = (known after apply)
      + lease_renewable       = (known after apply)
      + lease_start_time      = (known after apply)
      + path                  = "secret/password"
      + with_lease_start_time = false
    }
```


Plan after apply:
```
 <= data "vault_generic_secret" "passwords"  {
      ~ data                  = (sensitive value)
      ~ data_json             = (sensitive value)
      ~ id                    = "secret/password" -> (known after apply)
      ~ lease_duration        = 2764800 -> (known after apply)
      + lease_id              = (known after apply)
      ~ lease_renewable       = false -> (known after apply)
      + lease_start_time      = (known after apply)
      - version               = -1 -> null
        # (2 unchanged attributes hidden)
    }
```

**Comment by iehrenwald-linode** [comment]
@vinay-gopalan  I am seeing this drift too.  My use case is upgrading from Terraform 0.14.9 -> 0.15.5.  I've tried keeping the originally pinned Vault provider version of 3.7.0 and going to 3.9.0, and also adding `with_lease_start_time = false` to the `data` resource.

**Comment by fairclothjm** [comment]
Can you try using the `vault_generic_secret` resource instead of the data source?

### Some History
Before Terraform 0.13, data sources were only “read” during the apply phase. Things that depended on them down the dependency chain had to have their plans deferred until apply time. This caused some resources to be somewhat “un-planned” and have unknown values because they depended on a data source. With TF 0.13+ data sources are now read during the plan phase, providing better planning for resources that depend on them. This works great if your data sources don’t have side-effects like most of Vault’s do, which are typically dynamic credentials -- or in the case of this issue computing the current time for `lease_start_time`.
